AllCops:
  Exclude:
    - config/initializers/secret_token.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

StringLiterals:
  Enabled: false